- name: Install openebs repo
  when: inventory_hostname == groups["control"][0]
  kubernetes.core.helm_repository:
    repo_name: openebs
    repo_url: "{{ openebs_repo }}"
    repo_state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Install openebs
  when: inventory_hostname == groups["control"][0]
  kubernetes.core.helm:
    release_name: openebs
    release_namespace: openebs
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    release_state: present
    reuse_values: true
    atomic: true
    chart_ref: openebs/openebs
