- name: Ensure keyring dir
  tags:
    - kubetools
  ansible.builtin.file:
    path: '{{ kubetools_keyring.dir }}'
    mode: '0755'
    state: directory

- name: Add release key
  tags:
    - kubetools
  ansible.builtin.get_url:
    url: '{{ kubetools_keyring.url }}'
    dest: '/tmp/k8s-release.key'
    mode: '0644'
    force: true

- name: Dearmor release key
  tags:
    - kubetools
  ansible.builtin.command:
    argv:
      - gpg
      - --dearmor
      - --output
      - '{{ kubetools_keyring.dir }}/{{ kubetools_keyring.name }}'
      - '/tmp/k8s-release.key'
    creates: '{{ kubetools_keyring.dir }}/{{ kubetools_keyring.name }}'

- name: Add repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    enabled: true
    signed_by: '{{ kubetools_repo.signer }}'
    state: present
    types: [deb]
    suites: ['/']
    uris:
      - '{{ kubetools_repo.url }}'

- name: Install kubernetes packages
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: true

- name: Hold packages
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - kubeadm
    - kubelet
    - kubectl
