- name: Create cluster
  hosts: kubenet
  gather_facts: true
  gather_subset:
    - "!all"
    - default_ipv4
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: cluster
      tags:
        - cluster
