- name: Create cluster
  hosts: kubenet
  gather_facts: true
  gather_subset:
    - "!all"
    - default_ipv4
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: cluster
      tags:
        - cluster

- name: Install kube-vip
  hosts: control
  gather_facts: false
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: kvip
      tags:
        - kvip
      vars:
        kvip_version: v0.8.2

- name: Install helm
  hosts: control
  gather_facts: false
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: helm
      tags:
        - helm

- name: Install cilium
  hosts: kubenet
  gather_facts: false
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: cilium
      tags:
        - cilium

# - name: Install openebs
#   hosts: kubenet
#   gather_facts: false
#   become: true
#   become_user: root
#   become_method: ansible.builtin.sudo
#   roles:
#     - role: openebs
#       tags:
#         - openebs

- name: Install rook
  hosts: kubenet
  gather_facts: false
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: rook
      tags:
        - rook
