- name: Initialize Systems
  hosts: kubenet
  gather_facts: false
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: init
      tags: init
    - role: crio
      tags: crio
      vars:
        crio_version: v1.31
    - role: kubetools
      tags: kubetools

- name: Install kube-vip
  hosts: control
  gather_facts: false
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  roles:
    - role: kvip
      tags: kvip
      vars:
        kvip_version: v0.8.2
